name: movie_app
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  retrofit: ^4.7.2
  dio: ^5.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  equatable: ^2.0.7
  rxdart: ^0.28.0
  share_plus: ^11.1.0
  flutter_dotenv: ^6.0.0
  carousel_slider: ^5.1.1
  shimmer: ^3.0.0
  google_fonts: ^6.3.1
  connectivity_plus: ^6.1.5
  cached_network_image: ^3.4.1
  

dev_dependencies: 
  hive_generator: ^2.0.0
  retrofit_generator: ^8.2.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/
     - assets/images/
